apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment-label-key: deployment-label-value
  name: angular-app-deployment
  namespace: default

spec:
  minReadySeconds: 30
  replicas: 3
  selector:
    matchLabels:
      deployment-label-key: deployment-label-value
  template:
    metadata:
      labels:
        deployment-label-key: deployment-label-value
    spec:
      containers:
      - name: angular-app-container
        image: angular-app
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001