apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 3 # Set the number of replicas you want
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          imagePullPolicy: Never
          image: angular-app-image:latest # Specify the name of the Docker image you built earlier
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 256Mi
          ports:
            - containerPort: 4200 # Expose port 4200 from the container