apiVersion: v1
kind: Service
metadata:
  name: angular-app-balancer
spec:
  type: LoadBalancer # Use a LoadBalancer service to expose the app to the internet
  ports:
    - name: http
      port: 4200 # Expose port 80 on the service
      targetPort: 4200 # Forward traffic to port 4200 on the container
    - name: service-port-name
      port: 80
      protocol: TCP
  selector:
    app: angular-app