apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: {{ .Values.nameOverride}}
          imagePullPolicy: Never
          image: {{ .Values.image.tag}}
          resources:
            limits:
              cpu: "{{ .Values.container.resources.limits.cpu }}"
              memory: "{{ .Values.container.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.container.resources.requests.cpu }}"
              memory: "{{ .Values.container.resources.requests.memory }}"
          ports:
            - containerPort: {{ .Values.container.containerPort }}