apiVersion: v1
kind: Service
metadata:
  name: frontend-balancer
spec:
  type: LoadBalancer # Use a LoadBalancer service to expose the app to the internet
  ports:
    - name: http
      port: {{ .Values.container.containerPort }}
      targetPort: {{ .Values.container.containerPort }}
    - name: service-port-name
      port: {{ .Values.service.port}}
      protocol: {{ .Values.service.protocol | default "TCP" }}
  selector:
    app: angular-app