# Default values for fibserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2

image:
  pullPolicy: IfNotPresent
  tag: "fibserver"

imagePullSecrets: []
nameOverride: "fibserver-app"
fullnameOverride: "fibserver-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "fibserver"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 83

ingress:
  enabled: false
  className: ""
  annotations: {}

container:
  containerPort: 4000
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: "0.5"
      memory: 1048Mi


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90

nodeSelector: {}

tolerations: []

affinity: {}

