# Default values for market-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2

image:
  pullPolicy: IfNotPresent
  tag: "angular-app-image:latest"

imagePullSecrets: []
nameOverride: "market-app"
fullnameOverride: "market-app-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "market-app"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}

container:
  containerPort: 4200
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: "0.5"
      memory: 256Mi


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90

nodeSelector: {}

tolerations: []

affinity: {}

