replicaCount: 2

image:
  pullPolicy: IfNotPresent
  tag: "productservice"

imagePullSecrets: []
nameOverride: "productservice-app"
fullnameOverride: "productservice-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "productservice"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 82

ingress:
  enabled: true
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

container:
  containerPort: 3001
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: "0.5"
      memory: 256Mi


autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90

nodeSelector: {}

tolerations: []

affinity: {}
