apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 2 # Set the number of replicas you want
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "*"
        nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
        nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    spec:
      containers:
        - name: userservice-app
          imagePullPolicy: Never
          image: userservice:latest # Specify the name of the Docker image you built earlier
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 256Mi
          ports:
            - containerPort: 3000 # Expose port 3000 from the container